name: CI

on:
  push:
    branches: [master, next, alpha, beta]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstraping packages
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: Build package
        run: npm run prepare
      - name: Publish package
        if: always()
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
